Repository Kota8102/diary-app, pull requests merged in 2024-11, with the labels that each got.

#234 Feature/#233
  .github/workflows/pr-agent.yml
  .gitignore
  .pr_agent.toml
  src/frontend/src/components/layout/ContentLayout.tsx
  src/frontend/src/components/ui/Tab/Tab.tsx
  src/frontend/src/components/ui/Tab/TabItem.tsx
  src/frontend/src/components/ui/Tab/index.ts
  src/frontend/src/components/ui/Tab/types.ts
Labels: Review effort [1-5]: 2

#192 feat: Flower選択機能の追加と関連Lambdaの実装
  .gitignore
  docs/arch.drawio.svg
  package-lock.json
  src/backend/lambda/diary_create/diary_create.py
  src/backend/lambda/flower_generate/flower_generate.py
  src/backend/lambda/flower_select/__init__.py
  src/backend/lambda/flower_select/flower_select.py
  src/backend/lambda/flower_select/requirements.txt
  src/backend/lib/backend-stack.ts
  src/backend/lib/constructs/diary.ts
  src/backend/lib/constructs/flower.ts
  src/backend/lib/constructs/index.ts
  src/backend/package.json
  src/backend/test/__snapshots__/snapshot.test.ts.snap
  src/backend/test/pytest/test_diary_create.py
  src/backend/test/pytest/test_flower_select.py
Labels: Review effort [1-5]: 4

#236 feat: Add diary creation and flower display components
  package-lock.json
  src/frontend/package.json
  src/frontend/src/app/router.tsx
  src/frontend/src/app/routes/app/diary/diary-create.tsx
  src/frontend/src/app/routes/app/diary/diary-flower.tsx
  src/frontend/src/app/routes/app/diary/diary.tsx
  src/frontend/src/components/Elements/Header/Header.tsx
  src/frontend/src/components/layout/content-layout.tsx
  src/frontend/src/components/layout/index.ts
  src/frontend/src/components/ui/form/form.tsx
  src/frontend/src/components/ui/form/input.tsx
  src/frontend/src/components/ui/form/label.tsx
  src/frontend/src/components/ui/form/textarea-wrapper.tsx
  src/frontend/src/components/ui/form/textarea.tsx
  src/frontend/src/config/paths.ts
  src/frontend/src/features/diary/api/create-diary.tsx
  src/frontend/src/features/diary/componets/diary-create.tsx
  src/frontend/src/features/diary/componets/diary-select.tsx
  src/frontend/src/features/diary/componets/display-flower.tsx
  src/frontend/src/features/writeDiary/api/create-diary.ts
  src/frontend/src/types/api.ts
Labels: Review effort [1-5]: 4

#237 refactor: Modularize and style Calendar component
  src/frontend/src/app/routes/app/calendar.tsx
  src/frontend/src/components/layout/content-layout.tsx
  src/frontend/src/features/calendar/components/calendar.tsx
  src/frontend/src/features/calendar/styles/calendar.css
  src/frontend/src/features/diary/styles/calendar.css
Labels: Review effort [1-5]: 3

#248 feat: 設定画面にパスワード変更機能を追加
  src/frontend/src/app/router.tsx
  src/frontend/src/app/routes/app/setting/change-password.tsx
  src/frontend/src/app/routes/app/setting/setting.tsx
  src/frontend/src/assets/profileImage.png
  src/frontend/src/config/paths.ts
  src/frontend/src/features/setting/components/change-password-form.tsx
  src/frontend/src/features/setting/components/setting-menu.tsx
  src/frontend/src/features/setting/components/setting-profile.tsx
  src/frontend/tailwind.config.js
Labels: Review effort [1-5]: 4
